[package]
name = "double-ratchet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-array = "1.0.0"
zeroize = { version = "1.6.0", features = ["zeroize_derive"] }
